### ISSUE TITLE
still going backwards

### ISSUE THREAD

**Issue by slimslenderslacks** [atomist-skills/update-leiningen-dependencies-skill#21]
off-target atomist::common-clj atomist/common-clj/0.4.3-20200610140646 -> atomist/common-clj/0.4.3-20200610101448

140646 -> 101448

going backwards 4 hours.  Need to validate that things are working as expected with the semver lib

**Comment by kipz** [comment]
@slimslenderslacks AFAIK - semver does not treat the build qualifier as ordered in anyway....
