### ISSUE TITLE
Improve PR title to include pertinent information

### ISSUE THREAD

**Issue by kipz** [atomist-skills/update-leiningen-dependencies-skill#23]
No need to mention skill name etc, but talk about content and/or purpose for the change:

Title: *Update _atomist/aws-clj:1.2.3 ->  _1.2.4_ : latest in use*

Basically need to be able to take the decision based on title ideally.

**Comment by slimslenderslacks** [comment]
Let's just go with the above suggestion for now.  We still support PRs with more than one dependency update, and the body is a better place to show that.  However, showing the first dependency update in the title might be better.
